experiment:
  data_config:
    strategy: fixed
    dataset_path: ../data/{0}/trainingset.tsv
    train_path: ../data/{0}/trainingset.tsv
    validation_path: ../data/{0}/validationset.tsv
    test_path: ../data/{0}/testset.tsv
  dataset: amazon_men
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [Recall, nDCG, MAR, EPC, EFD, Gini, SEntropy, ItemCoverage]
  gpu: 0
  models:
    MultiVAE:
      meta:
        hyper_max_evals: 10
        hyper_opt_alg: tpe
        save_recs: False
        verbose: True
        validation_rate: 20
      lr: [ loguniform, -11.512925464970229, 0 ]
      epochs: 400
      batch_size: 256
      intermediate_dim: [ quniform, 300, 1200, 1 ]
      latent_dim: [ quniform, 100, 400, 1 ]
      dropout_pkeep: 0.5
      reg_lambda: [ loguniform, -11.512925464970229, 0 ]