experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/trainingset.tsv
    validation_path: ../data/{0}/validationset.tsv
    test_path: ../data/{0}/testset.tsv
  dataset: amazon_men
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [Recall, nDCG, MAR, EPC, EFD, Gini, SEntropy, ItemCoverage]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
   external.DGCF:
     meta:
       hyper_max_evals: 10
       hyper_opt_alg: tpe
       validation_rate: 20
       verbose: True
       save_weights: True
       save_recs: False
       validation_metric: Recall
       restore: False
     lr: [loguniform, -9.21034037198, -6.90775527898]
     epochs: 400
     factors: 64
     batch_size: 256
     l_w_bpr: [quniform, 10e-5, 10, 100]
     l_w_ind: [quniform, 10e-5, 10, 100]
     ind_batch_size: 256
     n_layers: 1
     routing_iterations: 2
     intents: 4