experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/trainingset.tsv
    validation_path: ../data/{0}/validationset.tsv
    test_path: ../data/{0}/testset.tsv
  dataset: amazon_baby
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [Recall, nDCG, MAR, EPC, EFD, Gini, SEntropy, ItemCoverage]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.NGCF:
      meta:
        hyper_max_evals: 10
        hyper_opt_alg: tpe
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 20
        validation_metric: Recall
        restore: False
      lr: [loguniform, -9.210340372, -5.298317367]
      epochs: 400
      factors: 64
      batch_size: 256
      l_w: [quniform, 10e-5, 10, 100]
      weight_size: (64,64,64)
      node_dropout: (0,0,0)
      message_dropout: (0.1,0.1,0.1)