experiment:
  data_config:
    strategy: fixed
    train_path: ../data/{0}/trainingset_explicit.tsv
    validation_path: ../data/{0}/validationset_explicit.tsv
    test_path: ../data/{0}/testset_explicit.tsv
    side_information:
      - dataloader: TextualAttributeSequence
        textual_features: ../data/{0}/document.all
  dataset: amazon_men
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [Recall, nDCG, MAR, EPC, EFD, Gini, SEntropy, ItemCoverage]
    relevance_threshold: 4
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.ConvMF:
      meta:
        hyper_max_evals: 10
        hyper_opt_alg: tpe
        verbose: True
        save_recs: False
        save_weights: False
        validation_rate: 20
      epochs: 400
      drop_out: [loguniform, -2.30258509299, 0 ]
      batch_size: 256
      l_u: [ quniform, 25, 150, 25 ]
      l_i: [ quniform, 25, 150, 25 ]
      embedding_size: 64
      factors_dim: 64
      kernel_per_ws: [ quniform, 25, 150, 25 ]
      give_item_weight: True